version: 0.2
phases:
  install:
    commands:
      - node --version
      - npm --version
  build:
    commands:
        - npm install
        - ./node_modules/.bin/standard
        - npm test
        - npm prune --production
  artifacts:
    files:
      - ./**/*