version: 0.2

phases:
  install:
    commands:
      - node --version
      - npm --version
  build:
    commands:
      - npm install
      - npm test
      - npm prune --production
artifacts:
  files:
    - ./**/*